[package]
name = "myhelper"
version = "1.0.0"
description = "myhelper"
authors = ["ialtone"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "myhelper_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.1", features = [] }

[dependencies]
image = "0.24.5" 
url = "2.5.2"
reqwest = { version = "0.12.7", features = ["blocking"] }
winapi = { version = "0.3.9", features = ["winbase", "winuser", "wingdi", "shellapi"] }
tauri = { version = "2.0.1", features = [ "protocol-asset", "tray-icon", "image-png"] }
tauri-plugin-shell = "2.0.1"
tauri-plugin-dialog = "2.0.1"
tauri-plugin-window-state = "2.0.1"
tauri-plugin-notification = "2.0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.40.0", features = ["full", "macros"] }
scraper = "0.20.0"
rand = "0.8.5"
open = "5.3.0"
clipboard-rs = "0.2.1"

[profile.dev]
opt-level = 0 #没有优化
debug = 0 #没有调试信息
strip = true #删除符号或调试信息
lto = false #禁用代码优化
