[package]
name = "myhelper"
version = "1.0.0"
description = "A Tauri App"
authors = ["ialtone"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "myhelper_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-rc.9", features = [] }

[dependencies]
image = "0.24.5" 
url = "2.5.2"
reqwest = { version = "0.12.7", features = ["blocking"] }
winapi = { version = "0.3.9", features = ["winbase", "winuser", "wingdi", "shellapi"] }
tauri = { version = "2.0.0-rc.10", features = ["tray-icon", "image-png"] }
tauri-plugin-shell = "2.0.0-rc.3"
tauri-plugin-dialog = "2.0.0-rc.5"
tauri-plugin-window-state = "2.0.0-rc.3"
tauri-plugin-notification = "2.0.0-rc.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = "1.40.0"
scraper = "0.20.0"

[profile.dev]
opt-level = 0 #没有优化
debug = 0 #没有调试信息
strip = true #删除符号或调试信息
lto = false #禁用代码优化
